### ISSUE TITLE
Typical proportions of unannotated cells?

### ISSUE THREAD

**Issue by onecarbon** [RGLab/FAUST#4]
I've used FAUST successfully on one dataset (12 markers), so thanks! I'm applying it now to a dataset with ~24 markers, and finding a large proportion of cells (40-60%) per sample are unannotated as '0_0_0_0_0'. Gates look sensible and most markers are clearly bimodal.

Is this the expected behaviour? It looks like there are two ways a cell can be unannotated: are there any parameters I can tune to explore this? Thanks for any advice.

**Comment by evangreene** [comment]
Happy to hear FAUST worked well for you on the 12 marker dataset!

Regarding the annotation behavior: this can be modified through tuning. The simplest way to reduce the number of unannotated cells is by setting the `nameOccuranceNum` parameter to 1 (this is assuming your gating set contains more than 10 samples). This will assign annotations to cells for all unique phenotypes proposed during the discovery phase of the process. One note: some cells will still have the phenotype "0_0_0_0_0". This happens because the proposed annotation for a cell does correspond to the observed expression measurements for the cell (before counts are generated for a sample, each cell is compared to the annotation thresholds for its experimental unit, and tested to make sure that the cell actually lies in the region described by the proposed annotation).

Another way to reduce the proportion of unannotated cells is to be more conservative in the marker selection conducted by FAUST. This can be tuned through the parameters `selectionQuantile` and `depthScoreThreshold`. FAUST generates a plot in `faustData/plotData` called `scoreLines.pdf`. If you post that plot here, I can comment on possible settings for your particular dataset suggested by the plot.

**Comment by onecarbon** [comment]
Great, thanks for the advice! I will try those out and get back to you on the scoreLines if I can't sort it.

**Comment by evangreene** [comment]
Closing this issue on the assumption the annotation percentages have been tuned. Please open another issue if further questions arise in the tuning process.
